title: Kennedy Toomey
tagline: Sharing my appsec learnings and experiences
description: An application security blog.
url: "https://kennedytoomey.github.io"
baseurl: ""

lang: en
timezone: America/New_York

social:
  name: Kennedy Toomey
  links:
    - https://github.com/kennedytoomey
    - https://www.linkedin.com/in/kennedy-toomey

analytics:
  google:
    id: G-2K1209X5TZ

datadog:
  application_id: "78755cee-98b7-4900-b4c5-ad86865a5b96"
  client_token: "pub25311cc0aed6dab1b130ede9f46b9013"
  site: "datadoghq.com"
  service: "kennedy-blog"
  env: "test-metadata"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: false

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - "*.gem"
  - "*.gemspec"
  - .github
